---
# VM Creation specific configuration
new_branch_name: "feature/{{ req_id }}-add-vm"  # Name for your new branch with request ID
commit_message: "feat: Add VM per {{ req_id }}"  # Commit message with request ID

# Pull Request Configuration
pr_title: "feat: Add VM per {{ req_id }}"  # Title for your pull request with request ID
pr_body: >-
  This pull request was automatically created by an Ansible playbook to add a new EC2 instance
  for request {{ req_id }}.
