---
# Phase 1: Create Pull Request for VM Creation
- ansible.builtin.import_playbook: vm-create-pr.yaml

# Phase 2: Wait for Checks and Merge Pull Request for VM Creation
- ansible.builtin.import_playbook: vm-merge-pr.yaml

# Phase 3: Get HCP Terraform Run Infos and Cost Estimates
- ansible.builtin.import_playbook: ../hcp-terraform/get-run-infos.yaml

# Software Management Phase
- ansible.builtin.import_playbook: ../windows-management/software-management.yaml
