- name: Create HCP Terraform Setup Job Template
  ansible.controller.job_template:
    name: "HCP Terraform Setup"
    description: "Run HCP Terraform setup playbook"
    job_type: "run"
    inventory: "Localhost"
    project: "{{ project_name }}"
    playbook: "ansible/hcp-terraform/setup-hcp-terraform.yaml"
    execution_environment: "{{ execution_environment_name }}"
    organization: "{{ default_organization }}"
    credentials:
      - "ansible-vault-password"
  tags: [job-templates, hcp-terraform]
