apiVersion: aap.ansible.com/v1alpha1
kind: AnsibleAutomationPlatform
metadata:
  name: aap-01
  namespace: aap
spec:
  # database:
  #   resource_requirements:
  #     requests:
  #       cpu: 200m
  #       memory: 512Mi
  #   storage_requirements:
  #     requests:
  #       storage: 100Gi

  controller:
    disabled: false

  eda:
    disabled: true

  hub:
    disabled: true
  #   storage_type: file
  #   file_storage_storage_class: <read-write-many-storage-class>
  #   file_storage_size: 10Gi