---
# controller_hosts:
#   - name: "localhost"
#     state: "{{ state | default('present') }}"
#     inventory: "Localhost"
#     variables:
#       ansible_connection: local
#       ansible_python_interpreter: "{{ ansible_playbook_python }}"
